baseURL = 'https://www.ayuhera.my.id/'
languageCode = 'en-us'
title = 'AYUHERA - Ayu Herawati'
theme = 'habitheme'

disableKinds = ["taxonomy", "taxonomyTerm"]

[[module.mounts]]
source = "static/images"
target = "assets/images"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4